### ISSUE TITLE
Why are mixins so flaky when it comes to versioning

### ISSUE THREAD

**Issue by cyberpwnn** [LXGaming/Sledgehammer#16]
```
[20:24:35] [main/WARN]: Mixin config mixins.sledgehammer.actuallyadditions.json requires mixin subsystem version 0.7.10 but 0.7.5 was found. The mixin config will not be applied.
[20:24:35] [main/WARN]: Mixin config mixins.sledgehammer.astralsorcery.json requires mixin subsystem version 0.7.10 but 0.7.5 was found. The mixin config will not be applied.
[20:24:35] [main/WARN]: Mixin config mixins.sledgehammer.bdsandm.json requires mixin subsystem version 0.7.10 but 0.7.5 was found. The mixin config will not be applied.
[20:24:35] [main/WARN]: Mixin config mixins.sledgehammer.bewitchment.json requires mixin subsystem version 0.7.10 but 0.7.5 was found. The mixin config will not be applied.
[20:24:35] [main/WARN]: Mixin config mixins.sledgehammer.carryon.json requires mixin subsystem version 0.7.10 but 0.7.5 was found. The mixin config will not be applied.
[20:24:35] [main/WARN]: Mixin config mixins.sledgehammer.champions.json requires mixin subsystem version 0.7.10 but 0.7.5 was found. The mixin config will not be applied.
[20:24:35] [main/WARN]: Mixin config mixins.sledgehammer.core.json requires mixin subsystem version 0.7.10 but 0.7.5 was found. The mixin config will not be applied.
[20:24:35] [main/WARN]: Mixin config mixins.sledgehammer.danknull.json requires mixin subsystem version 0.7.10 but 0.7.5 was found. The mixin config will not be applied.
[20:24:35] [main/WARN]: Mixin config mixins.sledgehammer.enderio.json requires mixin subsystem version 0.7.10 but 0.7.5 was found. The mixin config will not be applied.
[20:24:35] [main/WARN]: Mixin config mixins.sledgehammer.enderstorage.json requires mixin subsystem version 0.7.10 but 0.7.5 was found. The mixin config will not be applied.
[20:24:35] [main/WARN]: Mixin config mixins.sledgehammer.fluxnetworks.json requires mixin subsystem version 0.7.10 but 0.7.5 was found. The mixin config will not be applied.
[20:24:35] [main/WARN]: Mixin config mixins.sledgehammer.forge.json requires mixin subsystem version 0.7.10 but 0.7.5 was found. The mixin config will not be applied.
[20:24:35] [main/WARN]: Mixin config mixins.sledgehammer.immersiveengineering.json requires mixin subsystem version 0.7.10 but 0.7.5 was found. The mixin config will not be applied.
[20:24:35] [main/WARN]: Mixin config mixins.sledgehammer.integrateddynamicscompat.json requires mixin subsystem version 0.7.10 but 0.7.5 was found. The mixin config will not be applied.
[20:24:35] [main/WARN]: Mixin config mixins.sledgehammer.journeymap.json requires mixin subsystem version 0.7.10 but 0.7.5 was found. The mixin config will not be applied.
[20:24:35] [main/WARN]: Mixin config mixins.sledgehammer.kubejs.json requires mixin subsystem version 0.7.10 but 0.7.5 was found. The mixin config will not be applied.
[20:24:35] [main/WARN]: Mixin config mixins.sledgehammer.logisticspipes.json requires mixin subsystem version 0.7.10 but 0.7.5 was found. The mixin config will not be applied.
[20:24:35] [main/WARN]: Mixin config mixins.sledgehammer.matteroverdrive.json requires mixin subsystem version 0.7.10 but 0.7.5 was found. The mixin config will not be applied.
[20:24:35] [main/WARN]: Mixin config mixins.sledgehammer.morph.json requires mixin subsystem version 0.7.10 but 0.7.5 was found. The mixin config will not be applied.
[20:24:35] [main/WARN]: Mixin config mixins.sledgehammer.naturesaura.json requires mixin subsystem version 0.7.10 but 0.7.5 was found. The mixin config will not be applied.
[20:24:35] [main/WARN]: Mixin config mixins.sledgehammer.platform.json requires mixin subsystem version 0.7.10 but 0.7.5 was found. The mixin config will not be applied.
[20:24:35] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:199]: Failed to start Minecraft:
[20:24:35] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launch:231]: java.lang.reflect.InvocationTargetException
[20:24:35] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:24:35] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:24:35] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:24:35] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[20:24:35] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[20:24:35] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[20:24:35] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[20:24:35] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[20:24:35] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Required mixin config mixins.sledgehammer.platform.json requires mixin subsystem version 0.7.10
[20:24:35] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.mixin.transformer.MixinConfig.checkVersion(MixinConfig.java:417)
[20:24:35] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:331)
[20:24:35] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:894)
[20:24:35] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:116)
[20:24:35] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:91)
[20:24:35] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:78)
[20:24:35] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.addConfig(MixinPlatformManager.java:282)
[20:24:35] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.launch.platform.MixinPlatformAgentDefault.prepare(MixinPlatformAgentDefault.java:56)
[20:24:35] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.launch.platform.MixinContainer.prepare(MixinContainer.java:103)
[20:24:35] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.addContainer(MixinPlatformManager.java:146)
[20:24:35] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.scanClasspath(MixinPlatformManager.java:230)
[20:24:35] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:199)
[20:24:35] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:189)
[20:24:35] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.launch.MixinTweaker.injectIntoClassLoader(MixinTweaker.java:62)
[20:24:35] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[20:24:35] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[20:24:35] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	... 8 more
[20:24:35] [main/INFO]: [org.multimc.EntryPoint:main:37]: Exiting with -1
[20:24:35] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[20:24:35] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[20:24:35] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[20:24:35] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
[20:24:35] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:971)
[20:24:35] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.multimc.EntryPoint.main(EntryPoint.java:38)
Exception in thread "main" 
Process exited with code 1.
```

**Comment by cyberpwnn** [comment]
Im not using sponge, just the latest forge.

**Comment by LXGaming** [comment]
Can you please upload your debug.log or latest.log

According to what you have posted you are running a very old version of Mixin. You might be able to resolve the issue by renaming the Sledgehammer mod so the filename starts with an 'a' which should hopefully result in the Mixin shipping inside of Sledgehammer getting loaded instead of the ancient version.

**Comment by cyberpwnn** [comment]
I've renamed sledgehammer and that just causes another crash. Ive tried using the thin and sponge versions by actually installing sponge (as forgemod) but that just makes sponge ask for the same "clever rename trick".

I cant rename every damn mod that uses mixins to be the first to load. Is that literally the only solution? Is there no bootstrap for 1.12.2? Nearly every mod that uses mixins has a different version that doesnt work with any other mod using mixins and all of them want to load first to "work".

Why cant we all just go back to transforming classes with ASM. Sure its dirty, but it works better than this.

**Comment by LXGaming** [comment]
What is the error you are getting now? I have a feeling it might be the jar signing stopping it from loading.
